### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by Namchee** [Namchee/vue-ztext#1]
## Overview

Currently, this library doesn't have a running test suite yet. It seems that `@vue/test-utils` still breaks on TS + Vue 3 project.

## Mitigation

Setup a working test suite AND a runnable, passing sample test file.

**Comment by anatdagan** [comment]
Hi,
Please assign this issue to me

**Comment by Namchee** [comment]
@anatdagan 

I'm sorry, but I think my explanation for this issue is not clear enough.

The contribution I'm looking for is implementing test suite for testing vue 3 SFC component, NOT for testing normal JS and TS files.

Just a simple, passing `mount` and `shallowMount` will do

**Comment by anatdagan** [comment]
@Namchee 
Hi,
I've been making experiments adding a test suite to your project and reached the conclusion that for vue 3 we need to use https://github.com/vuejs/vue-test-utils-next/, as mentioned in the test-utils documentation: 
Vue Test Utils 1 targets Vue 2.
Vue Test Utils 2 (the link above) targets Vue 3.
The issue is that test utils next does not yet support shallowMount.
Implement it never the less, and just do mount test for now?

Thanks

**Comment by Namchee** [comment]
@anatdagan 

Thank you for your efforts!

I'm aware that we need the `next` version for `@vue/test-utils`, that's why this project uses `2.0.0-beta-5` as its dependency.
I didn't know about lack of `shallowMount` support though.

Yeah, just do a simple mount test and verify that it contains something.

**Comment by anatdagan** [comment]
Hi @Namchee ,
Where is the CSS object defined?

Thanks

**Comment by Namchee** [comment]
@anatdagan 

This project doesn't have any CSS on it. Users must style the component by themselves for now.

**Comment by anatdagan** [comment]
I mean in the component there is a line 
      if (
        CSS.supports('-moz-transform-style', 'preserve-3d') ||
        CSS.supports('-ms-transform-style', 'preserve-3d') ||
        CSS.supports('-webkit-transform-style', 'preserve-3d') ||
        CSS.supports('transform-style', 'preserve-3d')
      ) {

and jest throws an error that CSS is not defined

**Comment by anatdagan** [comment]
I see that this is browser native code. I'll try to mock it.

**Comment by Namchee** [comment]
Oh, I missed your point sorry. 

Yeah, that's a browser only variable.

**Comment by Namchee** [comment]
Closed by #2
